/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_edd;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;


/**
 *
 * @author simon
 */
//Ventana principal donde estan todas las funciones del programa
public class VentanaM extends javax.swing.JFrame {
    private String newJsonFilePath;
    private Sucursal sucursal;
    private Lista sucursales = new Lista();
    private Grafo grafo;

    /**
     * Creates new form VentanaM
     */
    public VentanaM(String newJsonFilePath, int t) {
        this.newJsonFilePath = newJsonFilePath;
        this.sucursal = new Sucursal(null);
        this.sucursal.setT(t);
        this.grafo = new Grafo();
        initComponents();
        textField2.setEditable(false);
        vOnly.setEditable(false);
        loadStations();
        grafo.loadFromJSON(newJsonFilePath);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        setT = new javax.swing.JButton();
        colocarSucursal = new javax.swing.JButton();
        searchDFS = new javax.swing.JButton();
        displayGrafo = new javax.swing.JButton();
        tField = new javax.swing.JTextField();
        textField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        searchBFS = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        vOnly = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        setT.setText("Establecer t");
        setT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTActionPerformed(evt);
            }
        });
        jPanel1.add(setT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        colocarSucursal.setText("Colocar sucursal");
        colocarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colocarSucursalActionPerformed(evt);
            }
        });
        jPanel1.add(colocarSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        searchDFS.setText("Ver cobertura sucursal (Busqueda a profundidad)*");
        searchDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDFSActionPerformed(evt);
            }
        });
        jPanel1.add(searchDFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        displayGrafo.setText("Mostrar Grafo*");
        displayGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayGrafoActionPerformed(evt);
            }
        });
        jPanel1.add(displayGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        tField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFieldActionPerformed(evt);
            }
        });
        jPanel1.add(tField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 50, -1));

        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        jPanel1.add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 260, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 210, 210));

        searchBFS.setText("Ver cobertura sucursal (Busqueda en Amplitud)*");
        searchBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBFSActionPerformed(evt);
            }
        });
        jPanel1.add(searchBFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jToggleButton1.setText("Guardar Archivo*");
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        jToggleButton2.setText("Agregar Linea*");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jToggleButton3.setText("Revisar Cobertura total*");
        jPanel1.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        vOnly.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vOnlyActionPerformed(evt);
            }
        });
        jPanel1.add(vOnly, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 250, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Boton para retroceder a la ventana anterior
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaP v1 = new VentanaP();
        this.dispose();
        v1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    //Boton para introducirvariable "t"
    private void tFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFieldActionPerformed
        
    }//GEN-LAST:event_tFieldActionPerformed
    //Boton para confirmar variable "t"
    private void setTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTActionPerformed
        try {
            int t;
            if (tField.getText().isEmpty()) {
                t = sucursal.getT();
                vOnly.setText("t: " + String.valueOf(t));
                System.out.println("Variable t predeterminada: " + t);
            }else {
                t = Integer.parseInt(tField.getText());
                if (sucursal != null){
                    sucursal.setT(t);
                    vOnly.setText("t: " + t);
                }else{
                    vOnly.setText("La sucursal no esta seleccionada.");
                }
            }
        }catch (NumberFormatException e){
            vOnly.setText("Ingrese un numero entero.");
        }
    }//GEN-LAST:event_setTActionPerformed
    //Boton para mostrar sucursales y acciones relacionadas
    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
            
    }//GEN-LAST:event_textField2ActionPerformed
    //Boton para confirmar sucursal seleccionada y añadirla a una lista o removerla
    private void colocarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colocarSucursalActionPerformed
        
    }//GEN-LAST:event_colocarSucursalActionPerformed
    //Boton de Busqueda en Profundidad
    private void searchDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDFSActionPerformed
            
    }//GEN-LAST:event_searchDFSActionPerformed
    //Boton que muestra el grafo 
    private void displayGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayGrafoActionPerformed
            grafo.display();
    }//GEN-LAST:event_displayGrafoActionPerformed
    //Boton de Busqueda en Amplitud
    private void searchBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBFSActionPerformed
       
    }//GEN-LAST:event_searchBFSActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void vOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vOnlyActionPerformed
        
    }//GEN-LAST:event_vOnlyActionPerformed
    //Metodo para leer las paradas del json y cargarlas como objetos en una JList
    private void loadStations() {
    if (newJsonFilePath != null) {
        try {
            File jsonFile = new File(newJsonFilePath);
            ObjectMapper mapper = new ObjectMapper();
            Map<String, List<Map<String, List<Object>>>> data = mapper.readValue(jsonFile, Map.class);
            DefaultListModel<String> listModel = new DefaultListModel<>();

            for (Map.Entry<String, List<Map<String, List<Object>>>> entry : data.entrySet()) {
                List<Map<String, List<Object>>> lines = entry.getValue();
                int lineaCounter = 1;
                for (Map<String, List<Object>> line : lines) {
                    String lineaName = "Linea " + lineaCounter;
                    for (Map.Entry<String, List<Object>> lineEntry : line.entrySet()) {
                        List<Object> stations = lineEntry.getValue();
                        for (Object station : stations) {
                            if (station instanceof Map) {
                                Map<String, String> transfer = (Map<String, String>) station;
                                for (Map.Entry<String, String> transferEntry : transfer.entrySet()) {
                                    listModel.addElement(lineaName + ": " + transferEntry.getKey() + " - " + transferEntry.getValue());
                                }
                            } else {
                                listModel.addElement(lineaName + ": " + station.toString());
                            }
                        }
                    }
                    lineaCounter++;
                }
            }
            jList1.setModel(listModel);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String newJsonFilePath = "";
                int t = 0;
                new VentanaM(newJsonFilePath, t).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colocarSucursal;
    private javax.swing.JButton displayGrafo;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JButton searchBFS;
    private javax.swing.JButton searchDFS;
    private javax.swing.JButton setT;
    private javax.swing.JTextField tField;
    private javax.swing.JTextField textField2;
    private javax.swing.JTextField vOnly;
    // End of variables declaration//GEN-END:variables
}
